### ISSUE TITLE
Add configurable notification message

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/EpicBanRequests#10]
Requested by @heyybro on spigotmc.org. Which is @Elango0 on github.com

**Comment by xBlockBuster98** [comment]
i don't understand, so i can modify the notifications??

**Comment by JustBru00** [comment]
You can't currently modify the notification message. This issue will be updated when I have a chance to add this feature.

**Comment by xBlockBuster98** [comment]
ok thx

**Comment by JustBru00** [comment]
Closed by 980954dc5f43e808f523511cdc6097ab5fa2a644
